# Generated by Django 2.1.5 on 2020-04-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app05', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='category',
            name='isdelete',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='news',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='news',
            name='isdelete',
        ),
        migrations.RemoveField(
            model_name='news',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='isdelete',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='updated_time',
        ),
    ]
