# Generated by Django 2.1.5 on 2020-04-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(default=1, max_length=16, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
